[build-system]
requires = [
    "setuptools >= 42.0",
    "setuptools-scm[toml] >= 3.4",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
exclude = '''
(
  /(
      \.git
    | \.tox
  )/
)
'''
line-length = 88

[tool.setuptools_scm]
write_to = "src/tox_no_deps/version.py"

[tool.pytest.ini_options]
addopts = "-ra --showlocals"

[tool.coverage.run]
parallel = true

[tool.coverage.report]
skip_covered = false
show_missing = true

[tool.coverage.paths]
source = [
    "src/tox-no-deps",
    "*/.tox/*/lib/python*/site-packages/tox-no-deps",
    "*/src/tox-no-deps",
]
